name: Gerar APK FinancialEX

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permissao ao Gradle
      run: chmod +x gradlew

    - name: Compilar o APK
      run: ./gradlew assembleDebug

    - name: Enviar o APK pronto
      uses: actions/upload-artifact@v4
      with:
        name: FinancialEX
        path: app/build/outputs/apk/debug/app-debug.apk
